# Generated by Django 2.1.2 on 2018-10-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0004_auto_20181011_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('couleur', models.CharField(max_length=150)),
                ('icone', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='charpak.Formation'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charpak.Promo'),
        ),
        migrations.AlterField(
            model_name='postfilactu',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
    ]
