# Generated by Django 2.1.2 on 2018-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0005_auto_20181018_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='profil_bac',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='statut',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='icone',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
