# Generated by Django 2.1.2 on 2018-11-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0006_auto_20181030_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='text',
            new_name='contenu',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='charpak.PostFilActu'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profils/'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='icone',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/icones/'),
        ),
    ]
