# Generated by Django 2.1.2 on 2018-11-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0008_auto_20181101_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='supprime',
            field=models.BooleanField(default=False),
        ),
    ]
