# Generated by Django 2.1.2 on 2018-11-02 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0010_auto_20181102_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='parain',
            new_name='parrain',
        ),
    ]
