# Generated by Django 2.1.2 on 2018-11-04 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0011_auto_20181102_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='etudiant', to=settings.AUTH_USER_MODEL),
        ),
    ]
