# Generated by Django 2.1.2 on 2018-11-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0012_auto_20181104_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilactu',
            name='couleur',
            field=models.CharField(choices=[('bleu', 'Promo'), ('rouge', 'Administration'), ('jaune', 'BDE'), ('vert', 'Public'), ('violet', 'Divers')], default='violet', max_length=150),
            preserve_default=False,
        ),
    ]
