# Generated by Django 2.1.3 on 2018-11-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0014_postfilactu_promo_ciblee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilactu',
            name='promo_ciblee',
            field=models.ManyToManyField(blank=True, default=None, related_name='posts', to='charpak.Promo'),
        ),
    ]
