# Generated by Django 2.1.3 on 2018-11-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0016_etudiant_bde'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='bde_pendant',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
