# Generated by Django 2.1.3 on 2018-11-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0017_promo_bde_pendant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='bde',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='bde_pendant',
        ),
    ]
