# Generated by Django 2.1.3 on 2018-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0020_auto_20181115_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bde',
            name='membres',
            field=models.ManyToManyField(default=None, related_name='membre_bde', to='charpak.Etudiant'),
        ),
    ]
