# Generated by Django 2.1.3 on 2018-11-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0021_auto_20181115_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='profil_bac',
            field=models.CharField(blank=True, choices=[('s-si', 'S-SI'), ('s-svt', 'S-SVT'), ('s', 'S'), ('sti', 'STI'), ('stl', 'STL'), ('sti2d', 'STI2D'), ('stav', 'STAV')], default=None, max_length=50, null=True),
        ),
    ]
