# Generated by Django 2.1.3 on 2018-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0022_auto_20181121_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bde',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/bde/'),
        ),
    ]
