# Generated by Django 2.1.3 on 2018-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0023_bde_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilactu',
            name='prive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postfilactu',
            name='couleur',
            field=models.CharField(choices=[('rouge', 'Administration'), ('jaune', 'BDE'), ('vert', 'Public')], max_length=150),
        ),
    ]
