# Generated by Django 2.1.3 on 2018-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpak', '0024_auto_20181206_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilactu',
            name='couleur',
            field=models.CharField(choices=[('rouge', 'Administration'), ('jaune', 'BDE'), ('violet', 'Divers')], max_length=150),
        ),
    ]
